---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir ~ '/vars/all.yml'}}"
  tasks:
    - name: Template compose file
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ playbook_dir ~ '/docker-compose.yml'}}"
    - name: Template sensu config
      template:
        src: ./templates/sensu_config.json.j2
        dest: "{{ sensu_server.buildroot ~ '/config.json' }}"
