---
- hosts: localhost
  gather_facts: false
  vars:
    buildroot: ./library
    rabbitmq:
      containername: rabbitmq
      user: sensu
      pass: sensu
      vhost: '/sensu'
    redis:
      containername: redis
    sensu_server:
      containername: sensu_server
      buildroot: "{{ buildroot ~ '/sensu-server' }}"
      imagename: sensu_server
    sensu_api:
      containername: sensu_api
      buildroot: "{{ buildroot ~ '/sensu-api'}}"
      imagename: sensu_api
  tasks:
    - name: Template compose file
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ playbook_dir ~ '/docker-compose.yml'}}"
    - name: Template sensu config
      template:
        src: ./templates/sensu_config.json.j2
        dest: "{{ sensu_server.buildroot ~ '/config.json' }}"
