---
- hosts: localhost
  gather_facts: false
  vars:
    buildroot: ./library
    rabbitmq:
      containername: rabbitmq
      user: sensu
      pass: sensu
      vhost: '/sensu'
    redis:
      containername: redis
      buildroot: "{{ buildroot ~ '/sensu-server' }}"
    sensu_server:
      containername: sensu_server
  tasks:
    - name: Template compose file
      template:
        src: templates/docker-compose.yml.j2
        dest: docker-compose.yml
    - name: Template sensu config
      template:
        src: ./templates/sensu_config.json.j2
        dest: "{{ sensu_server.buildroot ~ '/config.json' }}"
